### ISSUE TITLE
Navbar buttons missing with smaller window size

### ISSUE THREAD

**Issue by chris234567** [th-nuernberg/secure-questionnaire#11]
Having the app opened in a smaller window, possibly due to a smaller display resolution, will prevent the navbar from being rendered onto the screen. 
See greyed out HTML list in second screenshot.

![image](https://github.com/th-nuernberg/secure-questionnaire/assets/59069119/adaf7012-c96a-423e-b4d7-d020a787926c)
![image](https://github.com/th-nuernberg/secure-questionnaire/assets/59069119/88903e18-1b72-4dae-88be-10d448d47a8b)

**Comment by chris234567** [comment]
I would suggest stacking the elements, scaling them down in size or better yet package them into a menu button. This could become a frequent occurrence when using the app on a handheld device.

**Comment by tschadapa84654** [comment]
Fixed the navigation bar and added the optional missing button (b4ebdccedf8eee90b2522b86734209566cf62ca1)
