### ISSUE TITLE
"Fragebogen Erstellen"-Button doesn't work

### ISSUE THREAD

**Issue by ghost** [th-nuernberg/secure-questionnaire#12]
In CreateQuestionnaire.vue.

When clicking the "Fragebogen Erstellen"-Button to create a questionnaire, nothing changes visually and one is still on the same website. 

Error 404 Not found

ID Check of questionnaire fails.

**Comment by chris234567** [comment]
Nginx routing had a mix up with the addresses of frontend and backend containers.
See commit 1fe4c1b on June 26th.
